spring.application.name=springboot-siggy

#profile 선택
#spring.profiles.active=local
spring.profiles.active=prod

# Spring Boot 앱 포트
server.port=8082
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# MyBatis 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# JSP 수정 후 바로 반영
server.servlet.jsp.init-parameters.development=true